# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: smart/camera/camera.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'smart/camera/camera.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19smart/camera/camera.proto\x12\x0csmart.camera\x1a\x1bgoogle/protobuf/empty.proto\"\"\n\rCameraRequest\x12\x11\n\tcamera_id\x18\x01 \x01(\t\"7\n\x12TogglePowerRequest\x12\x11\n\tcamera_id\x18\x01 \x01(\t\x12\x0e\n\x06turnOn\x18\x02 \x01(\x08\"C\n\x11MoveCameraRequest\x12\x11\n\tcamera_id\x18\x01 \x01(\t\x12\r\n\x05\x61ngle\x18\x02 \x01(\x05\x12\x0c\n\x04tilt\x18\x03 \x01(\x05\"f\n\x0b\x43\x61meraState\x12\x11\n\tcamera_id\x18\x01 \x01(\t\x12\r\n\x05is_on\x18\x02 \x01(\x08\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\r\n\x05\x61ngle\x18\x04 \x01(\x05\x12\x0c\n\x04tilt\x18\x05 \x01(\x05\x12\n\n\x02ip\x18\x06 \x01(\t\"9\n\nCameraInfo\x12\x11\n\tcamera_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\"7\n\nCameraList\x12)\n\x07\x63\x61meras\x18\x01 \x03(\x0b\x32\x18.smart.camera.CameraInfo\"\x16\n\x03\x41\x63k\x12\x0f\n\x07message\x18\x01 \x01(\t2\x9a\x02\n\rCameraService\x12?\n\x0bListCameras\x12\x16.google.protobuf.Empty\x1a\x18.smart.camera.CameraList\x12\x42\n\x08GetState\x12\x1b.smart.camera.CameraRequest\x1a\x19.smart.camera.CameraState\x12\x42\n\x0bTogglePower\x12 .smart.camera.TogglePowerRequest\x1a\x11.smart.camera.Ack\x12@\n\nMoveCamera\x12\x1f.smart.camera.MoveCameraRequest\x1a\x11.smart.camera.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'smart.camera.camera_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAMERAREQUEST']._serialized_start=72
  _globals['_CAMERAREQUEST']._serialized_end=106
  _globals['_TOGGLEPOWERREQUEST']._serialized_start=108
  _globals['_TOGGLEPOWERREQUEST']._serialized_end=163
  _globals['_MOVECAMERAREQUEST']._serialized_start=165
  _globals['_MOVECAMERAREQUEST']._serialized_end=232
  _globals['_CAMERASTATE']._serialized_start=234
  _globals['_CAMERASTATE']._serialized_end=336
  _globals['_CAMERAINFO']._serialized_start=338
  _globals['_CAMERAINFO']._serialized_end=395
  _globals['_CAMERALIST']._serialized_start=397
  _globals['_CAMERALIST']._serialized_end=452
  _globals['_ACK']._serialized_start=454
  _globals['_ACK']._serialized_end=476
  _globals['_CAMERASERVICE']._serialized_start=479
  _globals['_CAMERASERVICE']._serialized_end=761
# @@protoc_insertion_point(module_scope)
