# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from smart.camera import camera_pb2 as smart_dot_camera_dot_camera__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in smart/camera/camera_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CameraServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListCameras = channel.unary_unary(
                '/smart.camera.CameraService/ListCameras',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=smart_dot_camera_dot_camera__pb2.CameraList.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/smart.camera.CameraService/GetState',
                request_serializer=smart_dot_camera_dot_camera__pb2.CameraRequest.SerializeToString,
                response_deserializer=smart_dot_camera_dot_camera__pb2.CameraState.FromString,
                _registered_method=True)
        self.TogglePower = channel.unary_unary(
                '/smart.camera.CameraService/TogglePower',
                request_serializer=smart_dot_camera_dot_camera__pb2.TogglePowerRequest.SerializeToString,
                response_deserializer=smart_dot_camera_dot_camera__pb2.Ack.FromString,
                _registered_method=True)
        self.MoveCamera = channel.unary_unary(
                '/smart.camera.CameraService/MoveCamera',
                request_serializer=smart_dot_camera_dot_camera__pb2.MoveCameraRequest.SerializeToString,
                response_deserializer=smart_dot_camera_dot_camera__pb2.Ack.FromString,
                _registered_method=True)


class CameraServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListCameras(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TogglePower(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveCamera(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CameraServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListCameras': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCameras,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=smart_dot_camera_dot_camera__pb2.CameraList.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=smart_dot_camera_dot_camera__pb2.CameraRequest.FromString,
                    response_serializer=smart_dot_camera_dot_camera__pb2.CameraState.SerializeToString,
            ),
            'TogglePower': grpc.unary_unary_rpc_method_handler(
                    servicer.TogglePower,
                    request_deserializer=smart_dot_camera_dot_camera__pb2.TogglePowerRequest.FromString,
                    response_serializer=smart_dot_camera_dot_camera__pb2.Ack.SerializeToString,
            ),
            'MoveCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveCamera,
                    request_deserializer=smart_dot_camera_dot_camera__pb2.MoveCameraRequest.FromString,
                    response_serializer=smart_dot_camera_dot_camera__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smart.camera.CameraService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('smart.camera.CameraService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CameraService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListCameras(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smart.camera.CameraService/ListCameras',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            smart_dot_camera_dot_camera__pb2.CameraList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smart.camera.CameraService/GetState',
            smart_dot_camera_dot_camera__pb2.CameraRequest.SerializeToString,
            smart_dot_camera_dot_camera__pb2.CameraState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TogglePower(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smart.camera.CameraService/TogglePower',
            smart_dot_camera_dot_camera__pb2.TogglePowerRequest.SerializeToString,
            smart_dot_camera_dot_camera__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smart.camera.CameraService/MoveCamera',
            smart_dot_camera_dot_camera__pb2.MoveCameraRequest.SerializeToString,
            smart_dot_camera_dot_camera__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
