# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from smart.fridge import fridge_pb2 as smart_dot_fridge_dot_fridge__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in smart/fridge/fridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FridgeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetState = channel.unary_unary(
                '/smart.fridge.Fridge/GetState',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=smart_dot_fridge_dot_fridge__pb2.FridgeState.FromString,
                _registered_method=True)
        self.GetFridgeTemperature = channel.unary_unary(
                '/smart.fridge.Fridge/GetFridgeTemperature',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=smart_dot_fridge_dot_fridge__pb2.TemperatureResponse.FromString,
                _registered_method=True)
        self.GetFreezerTemperature = channel.unary_unary(
                '/smart.fridge.Fridge/GetFreezerTemperature',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=smart_dot_fridge_dot_fridge__pb2.TemperatureResponse.FromString,
                _registered_method=True)
        self.SetFridgeTemperature = channel.unary_unary(
                '/smart.fridge.Fridge/SetFridgeTemperature',
                request_serializer=smart_dot_fridge_dot_fridge__pb2.TemperatureRequest.SerializeToString,
                response_deserializer=smart_dot_fridge_dot_fridge__pb2.Ack.FromString,
                _registered_method=True)
        self.SetFreezerTemperature = channel.unary_unary(
                '/smart.fridge.Fridge/SetFreezerTemperature',
                request_serializer=smart_dot_fridge_dot_fridge__pb2.TemperatureRequest.SerializeToString,
                response_deserializer=smart_dot_fridge_dot_fridge__pb2.Ack.FromString,
                _registered_method=True)
        self.GetLightStatus = channel.unary_unary(
                '/smart.fridge.Fridge/GetLightStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=smart_dot_fridge_dot_fridge__pb2.LightResponse.FromString,
                _registered_method=True)
        self.ToggleLight = channel.unary_unary(
                '/smart.fridge.Fridge/ToggleLight',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=smart_dot_fridge_dot_fridge__pb2.Ack.FromString,
                _registered_method=True)
        self.GetContents = channel.unary_unary(
                '/smart.fridge.Fridge/GetContents',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=smart_dot_fridge_dot_fridge__pb2.ContentsResponse.FromString,
                _registered_method=True)
        self.AddProductToFridge = channel.unary_unary(
                '/smart.fridge.Fridge/AddProductToFridge',
                request_serializer=smart_dot_fridge_dot_fridge__pb2.Item.SerializeToString,
                response_deserializer=smart_dot_fridge_dot_fridge__pb2.Ack.FromString,
                _registered_method=True)
        self.AddProductToFreezer = channel.unary_unary(
                '/smart.fridge.Fridge/AddProductToFreezer',
                request_serializer=smart_dot_fridge_dot_fridge__pb2.Item.SerializeToString,
                response_deserializer=smart_dot_fridge_dot_fridge__pb2.Ack.FromString,
                _registered_method=True)
        self.RemoveProductFromFridge = channel.unary_unary(
                '/smart.fridge.Fridge/RemoveProductFromFridge',
                request_serializer=smart_dot_fridge_dot_fridge__pb2.Item.SerializeToString,
                response_deserializer=smart_dot_fridge_dot_fridge__pb2.Ack.FromString,
                _registered_method=True)
        self.RemoveProductFromFreezer = channel.unary_unary(
                '/smart.fridge.Fridge/RemoveProductFromFreezer',
                request_serializer=smart_dot_fridge_dot_fridge__pb2.Item.SerializeToString,
                response_deserializer=smart_dot_fridge_dot_fridge__pb2.Ack.FromString,
                _registered_method=True)


class FridgeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFridgeTemperature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFreezerTemperature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFridgeTemperature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFreezerTemperature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLightStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ToggleLight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddProductToFridge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddProductToFreezer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveProductFromFridge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveProductFromFreezer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=smart_dot_fridge_dot_fridge__pb2.FridgeState.SerializeToString,
            ),
            'GetFridgeTemperature': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFridgeTemperature,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=smart_dot_fridge_dot_fridge__pb2.TemperatureResponse.SerializeToString,
            ),
            'GetFreezerTemperature': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFreezerTemperature,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=smart_dot_fridge_dot_fridge__pb2.TemperatureResponse.SerializeToString,
            ),
            'SetFridgeTemperature': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFridgeTemperature,
                    request_deserializer=smart_dot_fridge_dot_fridge__pb2.TemperatureRequest.FromString,
                    response_serializer=smart_dot_fridge_dot_fridge__pb2.Ack.SerializeToString,
            ),
            'SetFreezerTemperature': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFreezerTemperature,
                    request_deserializer=smart_dot_fridge_dot_fridge__pb2.TemperatureRequest.FromString,
                    response_serializer=smart_dot_fridge_dot_fridge__pb2.Ack.SerializeToString,
            ),
            'GetLightStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLightStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=smart_dot_fridge_dot_fridge__pb2.LightResponse.SerializeToString,
            ),
            'ToggleLight': grpc.unary_unary_rpc_method_handler(
                    servicer.ToggleLight,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=smart_dot_fridge_dot_fridge__pb2.Ack.SerializeToString,
            ),
            'GetContents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContents,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=smart_dot_fridge_dot_fridge__pb2.ContentsResponse.SerializeToString,
            ),
            'AddProductToFridge': grpc.unary_unary_rpc_method_handler(
                    servicer.AddProductToFridge,
                    request_deserializer=smart_dot_fridge_dot_fridge__pb2.Item.FromString,
                    response_serializer=smart_dot_fridge_dot_fridge__pb2.Ack.SerializeToString,
            ),
            'AddProductToFreezer': grpc.unary_unary_rpc_method_handler(
                    servicer.AddProductToFreezer,
                    request_deserializer=smart_dot_fridge_dot_fridge__pb2.Item.FromString,
                    response_serializer=smart_dot_fridge_dot_fridge__pb2.Ack.SerializeToString,
            ),
            'RemoveProductFromFridge': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveProductFromFridge,
                    request_deserializer=smart_dot_fridge_dot_fridge__pb2.Item.FromString,
                    response_serializer=smart_dot_fridge_dot_fridge__pb2.Ack.SerializeToString,
            ),
            'RemoveProductFromFreezer': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveProductFromFreezer,
                    request_deserializer=smart_dot_fridge_dot_fridge__pb2.Item.FromString,
                    response_serializer=smart_dot_fridge_dot_fridge__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smart.fridge.Fridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('smart.fridge.Fridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Fridge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smart.fridge.Fridge/GetState',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            smart_dot_fridge_dot_fridge__pb2.FridgeState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFridgeTemperature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smart.fridge.Fridge/GetFridgeTemperature',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            smart_dot_fridge_dot_fridge__pb2.TemperatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFreezerTemperature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smart.fridge.Fridge/GetFreezerTemperature',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            smart_dot_fridge_dot_fridge__pb2.TemperatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetFridgeTemperature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smart.fridge.Fridge/SetFridgeTemperature',
            smart_dot_fridge_dot_fridge__pb2.TemperatureRequest.SerializeToString,
            smart_dot_fridge_dot_fridge__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetFreezerTemperature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smart.fridge.Fridge/SetFreezerTemperature',
            smart_dot_fridge_dot_fridge__pb2.TemperatureRequest.SerializeToString,
            smart_dot_fridge_dot_fridge__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLightStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smart.fridge.Fridge/GetLightStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            smart_dot_fridge_dot_fridge__pb2.LightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ToggleLight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smart.fridge.Fridge/ToggleLight',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            smart_dot_fridge_dot_fridge__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smart.fridge.Fridge/GetContents',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            smart_dot_fridge_dot_fridge__pb2.ContentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddProductToFridge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smart.fridge.Fridge/AddProductToFridge',
            smart_dot_fridge_dot_fridge__pb2.Item.SerializeToString,
            smart_dot_fridge_dot_fridge__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddProductToFreezer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smart.fridge.Fridge/AddProductToFreezer',
            smart_dot_fridge_dot_fridge__pb2.Item.SerializeToString,
            smart_dot_fridge_dot_fridge__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveProductFromFridge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smart.fridge.Fridge/RemoveProductFromFridge',
            smart_dot_fridge_dot_fridge__pb2.Item.SerializeToString,
            smart_dot_fridge_dot_fridge__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveProductFromFreezer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smart.fridge.Fridge/RemoveProductFromFreezer',
            smart_dot_fridge_dot_fridge__pb2.Item.SerializeToString,
            smart_dot_fridge_dot_fridge__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
